# Generated by Django 5.0.2 on 2024-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizriesgo',
            name='gravedad',
            field=models.CharField(choices=[('Bajo2', 'Muy Bajo'), ('bajo1', 'Bajo'), ('medio', 'Medio'), ('alto1', 'Alto'), ('alto2', 'Muy Alto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matrizriesgo',
            name='probavilidad',
            field=models.CharField(choices=[('Bajo2', 'Muy Bajo'), ('bajo1', 'Bajo'), ('medio', 'Medio'), ('alto1', 'Alto'), ('alto2', 'Muy Alto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('I', 'Tipo I'), ('II', 'Tipo II'), ('III', 'Tipo III'), ('IV', 'Tipo IV')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fase',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('planeacion', 'Planeación'), ('ejecucion', 'Ejecución'), ('monitoreo_control', 'Monitoreo y Control'), ('cierre', 'Cierre')], max_length=100),
        ),
    ]
